language: c
services: docker

jobs:
  allow_failures:
    - arch: ppc64le

  include:
    - name: linux-arm32-gcc
      compiler: gcc
      script: test/ci/docker-arm32.sh

    - name: linux-arm32-clang
      compiler: clang
      script: test/ci/docker-arm32.sh

    - name: linux-powerpc-gcc
      compiler: gcc
      script: test/ci/docker-powerpc.sh

    - name: linux-arm64-gcc
      os: linux
      arch: arm64
      compiler: gcc
      env: NEON64_CFLAGS="-march=armv8-a"
      script: test/ci/generic.sh

    - name: linux-arm64-clang
      os: linux
      arch: arm64
      compiler: clang
      env: NEON64_CFLAGS="-march=armv8-a"
      script: test/ci/generic.sh

    - name: linux-s390x-gcc
      os: linux
      arch: s390x
      compiler: gcc
      script: test/ci/generic.sh

    - name: linux-ppc64le-gcc
      os: linux
      arch: ppc64le
      compiler: gcc
      script: test/ci/generic.sh
